### ISSUE TITLE
Conflict Error When Scaffolding Actian Zen V15 Database in Entity Framework Core

### ISSUE THREAD

**Issue by tromphakvoort** [ActianCorp/Actian.EFCore#12]
Hi,

Is there a repository available for the Actian Zen V15 Entity Framework Core data provider? I'm working with a Zen database from our ERP system, and I'd like to connect to it using EF Core.

Unfortunately, when I attempt to scaffold the database, I encounter the following error:

`The index named 'index_19' defined on properties {'RegelNummer'} cannot be added to the entity type 'Oreg (Dictionary<string, object>)' because an index with the same name already exists on entity type 'Oreg (Dictionary<string, object>)'.`

Since I don't have the option to modify the database schema directly, I'm hoping there might be a way to address this conflict within the scaffolding process itself. Any advice on how to resolve this issue or guidance on working around it would be greatly appreciated!

Thanks in advance!

**Comment by tromphakvoort** [comment]
Hi @clach04 , would you or one of your colleagues be able to assist with my question?

**Comment by clach04** [comment]
@tromphakvoort I have two answers for you, sadly Zen is outside of my area of expertise/confidence so none of my answers will get you a quick-fix 😿 :

1. This is definitely worth bringing up with the Zen team, initially via support (and potentially through your account manager).
2. Let me ping a buddy in the Zen team. I'm not aware of a Zen EFCore project (which doesn't mean there isn't one, it's just not on my radar). The practical thing to do **maybe** to simply skip EFCore and work with the provider directly (ergo SQL, rather than objects) , that last comment is an educated guess.

Final recommendation, I would chat with the ERP implementer, hitting the database directly outside of the scope of the ERP application **may** have unintended consequences (either locking if only reading and potentially worse when writing). It's really going to depend on the ERP system. See what advice they have about making direct database access.

I'm going to close this issue as this project specific to Ingres/Vector which is a different DBMS engine to Zen.

**Comment by jvarughe** [comment]
Use the --no-indexes option when scaffolding, which skips index creation. This can be helpful if you don’t need the indexes in the EF model directly, though it may slightly impact query performance. You can run.
dotnet ef dbcontext scaffold "YourConnectionString" Pervasive.Data.SqlClient --no-indexes
